### ISSUE TITLE
Confirm booking of Cardiff University for Thursday

### ISSUE THREAD

**Issue by inglesp** [PyconUK/pyconuk-2016-internaldocs#111]
@drvinceknight, can you let us know when the room bookings for the Thursday are confirmed?

Even better would be to update https://pyconuk-2016-internaldocs.readthedocs.io/en/latest/venue/, but I can do that.

**Comment by drvinceknight** [comment]
Will do :+1: :)

**Comment by drvinceknight** [comment]
Here are the rooms we have booked:
- Main lecture hall (for the main talks, capacity: 170): http://www.cardiff.ac.uk/estat/roombookings/cathays/bute/161bute/index.html

Other booked rooms:
- 053, capacity: 82 http://www.cardiff.ac.uk/estat/roombookings/cathays/bute/053bute/index.html
- 140, capacity: 72 http://www.cardiff.ac.uk/estat/roombookings/cathays/bute/140bute/index.html
- 150, capacity: 72 http://www.cardiff.ac.uk/estat/roombookings/cathays/bute/150bute/index.html
- 232, capacity: 71 http://www.cardiff.ac.uk/estat/roombookings/cathays/bute/232bute/index.html
- 228, capacity: 52 http://www.cardiff.ac.uk/estat/roombookings/cathays/bute/228bute/index.html (This has movable chairs)

These are all in a single building: http://www.cf.ac.uk/estat/accessibilityinformation/cathayscampus/butebuilding/buteaccess.html
