### ISSUE TITLE
Decide on code of conduct

### ISSUE THREAD

**Issue by inglesp** [PyconUK/pyconuk-2016-internaldocs#30]
The code of conduct we've used in previous years has lacked guidelines about how reports of problems will be dealt with.

It would be pragmatic to make use of a code of conduct that's battle-tested, and so I would like us to adopt PyCon US's [code of conduct](https://us.pycon.org/2016/about/code-of-conduct/)

**Comment by zeth** [comment]
It is very American, i.e. it goes on for a long time, is paranoid about sex
but says nothing about violence. Other than that seems fine. I thought our
old one was fine.

**Comment by inglesp** [comment]
Done.
