### ISSUE TITLE
Investigate ti.to for financial aid

### ISSUE THREAD

**Issue by inglesp** [PyconUK/pyconuk-2016-internaldocs#35]
Mock up form using ti.to that has [these questions](https://pyconuk-2016-internaldocs.readthedocs.org/en/latest/financial-aid/#proposed-questions).

**Comment by inglesp** [comment]
See https://ti.to/pyconuk/2016/with/g-qwyjfdj8c.  Feel free to create some dummy tickets.

**Comment by inglesp** [comment]
@Lukasa -- what do you think?

**Comment by Lukasa** [comment]
@inglesp Link doesn't work for me, shows "event not live"

**Comment by inglesp** [comment]
Have made you a moderator for the ti.to account -- try again.

**Comment by Lukasa** [comment]
So I think this is in principle fine. I have some concerns about wording of one of the questions:
- "Do you need a reserved ticket?" is really unclear. We need to rephrase: something like "Have you already registered for a ticket, or would you like one set aside for you until your grant is allocated?".

I'd also love to be able to provide an extended description for the first two questions to clarify how users should approach them. The first one should have a note that says something like "please try to be as realistic as possible: lower grants are more likely to be successfully funded than higher ones, but we'd rather you attended than not". The second one should have a note that explains that we're willing to set aside tickets for those who _require_ financial assistance to attend, but don't want to do so if the applicant has already bought the ticket.

Finally, I think we need a page to refer people to that explains how the financial aid process will work. I think coming up with that copy is on me though, yes?

**Comment by inglesp** [comment]
Agree with concerns about wording.  Now we know what the form looks like, could you update the [internal docs](https://pyconuk-2016-internaldocs.readthedocs.org/en/latest/financial-aid/#proposed-questions) with your proposed wording?

I've created https://github.com/PyconUK/pyconuk-2016-internaldocs/issues/40 to track writing copy for the financial aid page.

**Comment by inglesp** [comment]
We've decided against using ti.to.  See https://github.com/PyconUK/pyconuk-2016-internaldocs/issues/60.
