### ISSUE TITLE
Set up Google Form for CFP

### ISSUE THREAD

**Issue by inglesp** [PyconUK/pyconuk-2016-internaldocs#36]
First, add page to internal docs documenting questions asked.

**Comment by inglesp** [comment]
Hi @evildmp -- when do you think you'll get the chance to look at this?  Anything I can help with?

**Comment by evildmp** [comment]
@inglesp done, ready to launch once the CFP page is published on the site.

**Comment by inglesp** [comment]
Thanks @evildmp.

Some feedback on the form:
- I expect we'll want to close the CFP for posters after we close the CFP for talks.  Will this be possible?
- I've seen people get hung up on the difference between an "advanced" and an "intermediate" talk -- could we instead ask whether the talk is suitable for beginners?
- Can we add fields asking whether the session is "aimed at teachers" and "aimed at researchers"?
- Could we limit the description and the biography fields to say 300 words?
- Can we change the suggested tags from "ruby, javascript, rails"?
- You mention "themed gathering" in the text but it's not an option in the dropdown list of formats.  Should it be mentioned?

**Comment by snim2** [comment]
This is probably a very silly question, but where can I see the draft? Thanks.

**Comment by inglesp** [comment]
I think only @evildmp can share access to the CFP form on papercall.io.  We ought to record the questions in our documentation though, so I've created #44 which lists them.

**Comment by inglesp** [comment]
For various reasons, papercall.io seems not to be a good fit, so we have decided to use Google Forms instead.

**Comment by inglesp** [comment]
The only remaining task here is to make sure that people are emailed when their submission is accepted.  I have some App Script code to do this, which I'll set up tonight.

**Comment by inglesp** [comment]
@evildmp, where would you like to embed the CFP form?  There's a lot of text on http://2016.pyconuk.org/cfp/, and it's not immediately clear to me where the form should go.

**Comment by evildmp** [comment]
Let's link to the form, not embed it - they are not so nice embedded.
