### ISSUE TITLE
Set up redirect from pyconuk.org to 2016.pyconuk.org

### ISSUE THREAD

**Issue by inglesp** [PyconUK/pyconuk-2016-internaldocs#37]
I think only @zeth can do this, but we need to make sure that at least somebody else (@ghickman?) has access to these settings.

**Comment by zeth** [comment]
Yep @ghickman and I will be sorting this out.

**Comment by inglesp** [comment]
Hi @zeth, @ghickman -- when do you think this'll happen?

**Comment by inglesp** [comment]
Paging @zeth and @ghickman...

**Comment by ghickman** [comment]
@zeth has kindly created a separate 123-reg account for us to use. I'll be getting this set up further some time in the next few days.

**Comment by ghickman** [comment]
Fixed with a [URL record](https://support.dnsimple.com/articles/url-record/) on DNSimple.
