### ISSUE TITLE
Set up sponsorship spreadsheet

### ISSUE THREAD

**Issue by inglesp** [PyconUK/pyconuk-2016-internaldocs#42]
We need to be able to track:
- Sponsor/potential sponsor's name
- Who we've been in contact with (name and email address)
- Who's leading discussions on our end
- The current status of discussions -- one of:
  - Contacted
  - Not sponsoring
  - Sponsorship agreed
  - Sponsorship received
- Date of last contact
- The agreed sponsorship package
- Any extra notes

Alternatively, we could investigate using a CRM for this (and I'd be happy for us to pay for the right one) but we need to get this set up soon.

To be assigned to Paul when he joins the GitHub team.

**Comment by inglesp** [comment]
This is done.

**Comment by doismellburning** [comment]
@inglesp / @lifeisstillgood Do either of you have a link to this perchance please?

**Comment by inglesp** [comment]
@doismellburning It's in the shared Google folder, but I'll send you the link on Slack.

**Comment by lifeisstillgood** [comment]
Sorry late catching up on emails.  If by some strange alien abduction event peter did not post it please shout again

## Yours

Paul Brian
paul@mikadosoftware.com
07540456115
@lifeisstillgood

> On 11 Jul 2016, at 10:17, Peter Inglesby notifications@github.com wrote:
> 
> @doismellburning It's in the shared Google folder, but I'll send you the link on Slack.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.

## 

www.mikadosoftware.com

See your software improve with every change.
