### ISSUE TITLE
Set up system for invoicing sponsors

### ISSUE THREAD

**Issue by inglesp** [PyconUK/pyconuk-2016-internaldocs#43]
Assigned to @doismellburning, but you should work with Paul (who's not yet part of the GitHub team).

**Comment by doismellburning** [comment]
I'm assuming Paul has more context here!

**Comment by snim2** [comment]
Is there an ETA on this? Thanks.

**Comment by doismellburning** [comment]
@snim2 Anything I can do for you here?

**Comment by snim2** [comment]
@doismellburning thanks; I may need to raise an invoice in the next 10 days or so (for sponsor), is that possible?

**Comment by inglesp** [comment]
This is done (see https://pyconuk-2016-internaldocs.readthedocs.io/en/latest/sponsorship/#invoicing).
