### ISSUE TITLE
Write page for Code4Research track

### ISSUE THREAD

**Issue by inglesp** [PyconUK/pyconuk-2016-internaldocs#52]
We need a page on the website about the Code4Research track.  It should act as a landing page for the track.

We will link to the page from the homepage.

It should include links to the tickets page, to the CFP, and to the financial aid page.

I suggest it goes at 2016.pyconuk.org/code4research.

**Comment by inglesp** [comment]
Hi @snim2 -- when do you think you'll get the chance to look at this?

**Comment by snim2** [comment]
I'm nearly finished with a draft and expect to be pushing a PR later tonight, apologies for the delay
