### ISSUE TITLE
Set up Google Form for financial aid

### ISSUE THREAD

**Issue by inglesp** [PyconUK/pyconuk-2016-internaldocs#60]
We should use the questions identified by @Lukasa [here](https://pyconuk-2016-internaldocs.readthedocs.org/en/latest/financial-aid/#proposed-questions).

We should also ensure that people are notified by email that we have received their submission.  I have some App Script code to do this.

**Comment by inglesp** [comment]
This form is set up.

@Lukasa, where would you like the form to go on the site?

**Comment by Lukasa** [comment]
I think we should provide it from the financial aid page, at the very top, and then make sure we're prominently linking the fin aid page from the CFP page and front page. =)
