### ISSUE TITLE
Set up system for teachers to apply for bursaries

### ISSUE THREAD

**Issue by inglesp** [PyconUK/pyconuk-2016-internaldocs#62]
The website says this we'll do this by May 1st, so we'd better do it by then!

**Comment by inglesp** [comment]
Having discussed this with Carrie Anne and Nicholas, we'll do something similar to last year.
- We'll collect bursary applications via a separate ticket type on Tito, collecting information on:
  - name of school
  - address of school
  - number of students they teach
  - level: primary, middle, secondary, post-16
  - level of Python experience: none, some, a lot, tons
- We'll need to make it clear that people must also buy a ticket to the conference
- We'll allocate bursaries on a first-come-first-served basis
- At the conference, people can collect a form to be filled in by their school's bursar
- They'll post this form to somebody who can then process the payment to the school

We will be limited to 40 bursaries in the first instance.

@doismellburning, as treasurer, do you see any problems with this?

**Comment by doismellburning** [comment]
What _is_ a bursary in concrete terms? £200 cash? I have 15k in a general bursary/FinAid pot with 10k earmarked for bursaries based on last year

(Did you see chat in #education?)

**Comment by doismellburning** [comment]
..yes you did see chat in #education because you pasted a link here in there!

**Comment by inglesp** [comment]
This is done.  #112 covers the claiming of bursaries.
