### ISSUE TITLE
Contact hotels regarding preferential rate for conference

### ISSUE THREAD

**Issue by inglesp** [PyconUK/pyconuk-2016-internaldocs#66]
Start with the hotels at http://2015.djangocon.eu/welcome/accommodation/.

**Comment by inglesp** [comment]
Assigning this to @evildmp as he's already started doing it.

**Comment by evildmp** [comment]
Pull request waiting for review. https://github.com/PyconUK/2016.pyconuk.org/pull/64

**Comment by snim2** [comment]
FYI If you say "Fixes <URL>" on the "conversation" of a PR, the Issue will be closed automatically when the PR is merged. This works even if the Issue is in a different repo to the PR. No need to close issues manually!
