### ISSUE TITLE
Set up email address for contacting suppliers etc

### ISSUE THREAD

**Issue by inglesp** [PyconUK/pyconuk-2016-internaldocs#67]
@evildmp has suggested that we use a email address for contacting suppliers etc.  This sounds like a good idea!

**Comment by inglesp** [comment]
@ghickman, could you try to set up pyconuk@gmail.com?

**Comment by ghickman** [comment]
@inglesp – sure thing, when do you need it by?

**Comment by inglesp** [comment]
End of the week?

**Comment by ghickman** [comment]
Sure thing.

**Comment by evildmp** [comment]
Not just suppliers, but speakers, complainants, the press, etc.

**Comment by evildmp** [comment]
@ghickman hello, sorry to be a nuisance, could we have this set up? It would be most useful.

**Comment by ghickman** [comment]
@evildmp – not a nuisance at all! I'm already on it, currently trying to track down who has pyconuk@gmail.com already registered, stay tuned.  If I don't get a response by tomorrow I'll set something else up.

**Comment by ghickman** [comment]
@evildmp – we now have `pyconukorganisers@gmail.com`, I'll send you the password privately.
