### ISSUE TITLE
Add "Supporter Ticket" type to ti.to

### ISSUE THREAD

**Issue by inglesp** [PyconUK/pyconuk-2016-internaldocs#84]
We've promised we'd do this on the [diversity/accessibility/inclusion](http://2016.pyconuk.org/diversity-accessibility-inclusion/) page.

**Comment by inglesp** [comment]
We can make this ticket a "donation" type ticket, where people choose how much to contribute.

@doismellburning, wearing your your legal/treasurer hat, do you see any problems with this?

As for the ticket description, how about something like:

"Include a donation to help buy a ticket on behalf of an attendee who couldn’t otherwise afford it"

@evildmp, does this match your expectations?

**Comment by evildmp** [comment]
How about: "Every penny we receive will go be added to our existing budget for financial assistance, to support the attendance of someone who'd otherwise find it hard to afford." 

But yes, that kind of thing.

**Comment by doismellburning** [comment]
> We can make this ticket a "donation" type ticket, where people choose how much to contribute.
> @doismellburning, wearing your your legal/treasurer hat, do you see any problems with this?

Assuming we're talking "choose > existing ticket price" SGTM!

**Comment by inglesp** [comment]
@evildmp, that's a little too long for the Tito form, so I think I'll stick with my original phrasing.

@doismellburning, I wasn't clear, sorry.  I'm actually proposing using an extra ticket type for the supporter ticket, as it decouples the process of buying a ticket for yourself from the process of contributing to financial assistance.  Happy with that?

**Comment by doismellburning** [comment]
@inglesp Sorry for my ambiguity too - as long as we're talking "more revenue than I initially planned" it SGTM!

**Comment by inglesp** [comment]
This is done.
