### ISSUE TITLE
Add notes to website about resources for people of faith

### ISSUE THREAD

**Issue by inglesp** [PyconUK/pyconuk-2016-internaldocs#87]
This follows a discussion on the mailing list.

Assigning to @Lukasa who brought up the issue originally.

**Comment by inglesp** [comment]
On https://github.com/PyconUK/2016.pyconuk.org/pull/74, @Lukasa said "This doesn't address the question of a prayer room, which is as-yet unresolved".

Now this is closed, do we need a new issue for that?

**Comment by Lukasa** [comment]
Probably, or we can re-open this.

**Comment by meshy** [comment]
Sorry -- I guess I got a little overenthusiastic and jumped the gun a little there `:/`

**Comment by Lukasa** [comment]
@meshy Nah, GitHub closed this for you. That's my bad for the wording I used in the other issue.

**Comment by meshy** [comment]
Cool. :+1:
