### ISSUE TITLE
There's no option for proposing a sprint in the CFP

### ISSUE THREAD

**Issue by inglesp** [PyconUK/pyconuk-2016-internaldocs#95]
From a Slack channel I belong to:

"BTW: Page 1 (http://2016.pyconuk.org/code-day/) "tell us about your sprint “ links to Page 2 (http://2016.pyconuk.org/cfp/) which doesn’t mention that or have any particular way for me to tell you about my sprint.

I don’t even have a sprint at the moment, so it’s not that important.

But If I did, I would definitely be confused."

**Comment by evildmp** [comment]
"Something completely different" doesn't cover all options not listed?

**Comment by inglesp** [comment]
Can see what you mean (see also [These two books contain the sum total of all human knowledge](http://imgur.com/gallery/oEXYFZw)) but it's confused at least one person, and I think if we're asking for people to submit sprints, we should make it as easy as possible for them.

I'll leave it to you to decide whether to update the CFP or close this issue.

**Comment by evildmp** [comment]
I'll do it!

**Comment by evildmp** [comment]
Done.
