### ISSUE TITLE
Decide whether to give away t-shirts, or sell them as extras

### ISSUE THREAD

**Issue by inglesp** [PyconUK/pyconuk-2016-internaldocs#96]
Other conferences (eg PyCon and Djangocon in the US) sell conference t-shirts rather than giving them away.  Any money raised is used for supporting a good cause.

Arguments for giving them away:
- We've always done it, and people may expect it

Arguments for selling them:
- They're quite an expensive per-person cost
- They're a pain to manage
- Many people never wear their t-shirts

If anybody has feelings either way, please comment below.

**Comment by ghickman** [comment]
I'm all for selling them, delegates are free to buy them if they want and we don't end up wasting money and more importantly time on unused extras.

Any t-shirts sold would ideally be sold as "buy a t-shirt and help PyCon UK" much as PyCon US sells them expressly to help the PSF.

**Comment by MissMaximas** [comment]
I agree with selling them. If people are expecting the t-shirts to be free, I think we could safely assume that they've been to at least one of the previous PyConUK conferences and have decided to attend again because they enjoyed the conference itself (And may also already have a t-shirt).

What would happen with the money raised by this?

**Comment by doismellburning** [comment]
Has anyone thought much about the logistics of selling them?
- How many do we want to order / do we expect to sell?
- What do we price them at?
- What do we do with left-over inventory (I've no idea what we've done previously, but "give them away enthusiastically" may not be appropriate for stuff we're selling)

**Comment by inglesp** [comment]
Rather than buying up inventory in advance (with the problem of what to do if we over/under-provision) we should find a website that sells t-shirts, and direct people to that.

This is what DjangoCon US have done.  See [here](https://2015.djangocon.us/blog/2015/09/05/conference-t-shirt/) for more details.  They used Teespring and Fabrily, and it looks like they were selling t-shirts for around £15.

**Comment by doismellburning** [comment]
...that is infinitely more sensible, yes, good call!

**Comment by doismellburning** [comment]
(Sorry, was stuck in "getting t-shirts printed" thought-mode)

**Comment by doismellburning** [comment]
Alright. Who owns this? Is it going to be @inglesp by default again? ;P

**Comment by doismellburning** [comment]
I'm willing to own this unless anyone else is keen

(I'm going to regret that aren't I)

**Comment by inglesp** [comment]
Thanks @doismellburning!  I'm sure you'll do a great job...

Perhaps you could open some new issues to track what needs doing here.  (This issue's all about deciding whether to give t-shirts away or not.)

**Comment by doismellburning** [comment]
Will do, cheers

**Comment by doismellburning** [comment]
**Conclusion**: No, we're selling via some sort of on-demand service, I'm on it
