### ISSUE TITLE
Ensure timings of teachers' day track fits in with rest of schedule

### ISSUE THREAD

**Issue by inglesp** [PyconUK/pyconuk-2016-internaldocs#99]
Carrie Anne and @evildmp should have a chat about this.

**Comment by MissPhilbin** [comment]
An overview of timings for the day would be useful for scheduling the teachers track. e.g. when is lunch ;)

**Comment by MissPhilbin** [comment]
Any progress on this? @evildmp @inglesp 

I need similar for the kids day to put together the agenda.

**Comment by evildmp** [comment]
Yes, this is all in the skeleton schedule! I will ping you on Slack and we can talk about it.
